### PR TITLE
Refactor for RC version

### PR DESCRIPTION
**Pull request by gbrlsnchs**
This is a WIP  refactor that will compose the new major release version, `v3`. Some missing features will still be added and soon this will be merged and released as an RC version.

Some missing features are:
* ~A custom type for epoch time~ DONE
* ~Tests for `Verify`~ DONE
* ~More test cases for `Sign`~ DONE
* ~Compatibility with `go1.9.7`, `go1.10.3`, `go1.11` onward (#26)~ DONE
* ~CI made by CircleCI (#28)~ DONE

The only feature that won't be in the initial version of `v3` is JWT encryption, which will be developed later, if possible.

### CODE REVIEW

**Comment by gbrlsnchs** [comment]
@metala Hey, you seem to be involved with the latest beta versions I've been releasing and you were also the one who asked me about validating the header "alg" claim before verifying the signature.

I told you about the `Decoder` but I still think it introduces too much work for developers. I want the API to be very simple, and recently I learned about functional options and wanted to use it here.

Therefore, with this PR, there'll only be two main functions, `jwt.Sign` and `jwt.Verify`, and extra configuration/validation is done via functional options. For example, with `Decoder` you had to do:
```go
var pl jwt.Payload
err := jwt.NewDecoder(token, alg).Decode(&pl)
if err != nil {
	// handle error
}
```

But now, every extra validation is centralized in `jwt.Verify`:
```go
var pl jwt.Payload
err := jwt.Verify(token, alg, jwt.ValidateHeader, jwt.DecodePayload(&pl))
if err != nil {
	// handle error
}
```

I just wanted your opinion before I merge this branch to `master`, and I promise this might be the last time the API is changed, as I hope to release `v3` soon.
```

**Comment by gbrlsnchs** [comment]
@seh Hello, you opened an issue about using a pointer for numeric dates. Well, I decided to implement your suggestion, so I would like to hear your opinion on how it's done in this branch. You can check the examples at https://github.com/gbrlsnchs/jwt/tree/feature-refactor. This branch will be merged to `master`, which will become a release candidate for `v3`. Thanks!

**Comment by seh** [comment]
I've been watching the recent flurry of commits, which is so good to see. We've had the stable use in use in a production system for several months, and it works all day long like a champ.

On the subject of time, we're thinking back to #24 here. I noticed that as of today, in [`(*jwt.Time).MarshalJson`](https://github.com/gbrlsnchs/jwt/blob/feature-refactor//time.go#L28-L34), you [write a value of zero](https://github.com/gbrlsnchs/jwt/blob/feature-refactor//time.go#L31) to indicate absence. My reading of RFC 7519's use of "OPTIONAL" is that it's better to omit the claim field entirely in the JSON serialization. Looking around on the Web for discussion of the RFC, I did find one article—"A Look at The Draft for JWT Best Current Practices"—that contains [this sentence](https://auth0.com/blog/a-look-at-the-latest-draft-for-jwt-bcp/#Validate.All.Possible.Claims):
> For this reason, claims such as `sub` (subject), `exp` (expiration time), `iat` (issued at), `aud` (audience), `iss` (issuer), `nbf` (not valid before) are of the utmost importance and should always be validated **when present**.

The emphasis at the end is mine. I take it to confirm that omitting time-related fields indicates that the token makes no statement on that front.

Since your `jwt.Payload` struct type uses both a pointer for [these time-related fields](https://github.com/gbrlsnchs/jwt/blob/feature-refactor/payload.go#L8-L10) and tags them with "omitempty," you'll properly omit them in the JSON when the `Payload` lacks non-nil values for those fields. I'm not sure that the nil check in `jwt.Time.IsZero` will ever catch, given the "omitempty" tag.

If a caller inspecting a `jwt.Payload` finds a nil `*jwt.Time` value and calls `IsZero` on it, the result is misleading; the lack of the field means that, say, there is no expiration, and not that the token expires on the epoch. Now, the caller could have first tested for the field value being nil to make that finer distinction, but I'd rather have `jwt.Time.IsZero` panic when called on a nil receiver or, better yet, have the receiver type be a concrete `jwt.Time` and not a `*jwt.Time`, which makes this meaning clearer: You can't have a zero time if you don't even have a time.

During verification, we need to look up the signing key by the "kid" header field's value, so, if I understand your interface change here, we'll still need to use two steps. I see [the new `jwt.DecodeHeader` function](https://github.com/gbrlsnchs/jwt/blob/feature-refactor/verify.go#L49-L60), but it looks like that's used by `jwt.Verify`, at which point we already have already committed to an expected algorithm. Can you walk me through which functions and types we'd use today to do the following?
- Decode token into header and payload
- Inspect header to read "kid" field to learn which key signed this token
- Prepare a `Verifier` for this key
- Verify that the token was signed by this key

**Comment by gbrlsnchs** [comment]
> Can you walk me through which functions and types we'd use today to do the following?
> 
>     * Decode token into header and payload
> 
>     * Inspect header to read "kid" field to learn which key signed this token
> 
>     * Prepare a `Verifier` for this key
> 
>     * Verify that the token was signed by this key

Oops! Currently this isn't possible. I didn't have that use case in mind. That made me realize that the way I'm designing the `jwt.Verify` method is a little flawed. Therefore, I've taken a look at the RFC again and also realized that checking whether the JWT parts are Base64-decodable and valid JSON is mandatory:

> 3.   Base64url decode the Encoded JOSE Header following the
        restriction that no line breaks, whitespace, or other additional
        characters have been used.
> 4.   Verify that the resulting octet sequence is a UTF-8-encoded
        representation of a completely valid JSON object conforming to
        RFC 7159 [RFC7159]; let the JOSE Header be this JSON object.

and

> 9.   Otherwise, base64url decode the Message following the
        restriction that no line breaks, whitespace, or other additional
        characters have been used.
> 10.  Verify that the resulting octet sequence is a UTF-8-encoded
        representation of a completely valid JSON object conforming to
        RFC 7159 [RFC7159]; let the JWT Claims Set be this JSON object.

This way, I'm thinking of changing the signature of `jwt.Verify` to the following:
```go
func Verify(token []byte, alg Algorithm, payload interface{}, opts ...VerifyOption) (jwt.Header, error)
```

Yes, I know, it's freaking big and forces lower performance by decoding and unmarshaling two structs (`payload` and the `jwt.Header` returned), however being RFC-compliant comes first.

Also, regarding your use case: I've been thinking for a while about adding a `jwtutil` package with some tools for people to build their custom algorithms for signing and decoding (because why not?), like the hashing function pool currently being used internally to avoid too many allocations. I think adding a `Resolver` to such package would be a great fit. The `jwtutil.Resolver` would work like an `jwt.Algorithm` factory, and the function that resolves which `jwt.Algorithm` should be returned would be part of the application logic. Something like this:
```go
import (
	"errors"

	"github.com/gbrlsnchs/jwt/v3"
	"github.com/gbrlsnchs/jwt/v3/jwtutil"
)

var (
	// ...

	rs256 = jwt.NewRS256(nil, myRSAKey)
	es256 = jwt.NewES256(nil, myECDSAKey)
)

func main() {
	rv := &jwtutil.Resolver{New: func(hd jwt.Header) {
		switch hd.KeyID {
		case "foo":
			return rs256, nil
		case "bar":
			return es256, nil
		default:
			return nil, errors.New(`invalid "kid"`)
		}
	}}
	var pl jwt.Payload
	if _, err := jwt.Verify(token, rv, &pl); err != nil {
		// ...
	}

	// ...
}
```

The `jwtutil.Resolver` is just a wrapper that internally sets an internal variable to an `jwt.Algorithm` and uses it for its methods that implement the `jwt.Algorithm`. Thus, unlike the predefined algorithms, it isn't reusable, although the algorithms it picks are.

Now, regarding `jwt.Time`, the marshaling method needs to resolve the value marshaled because, as per the RFC, the value can't be less than 0. However, thanks to `omitempty` and the `jwt.NumericDate` helper, this will not happen unless someone uses a raw `jwt.Time` pointer.

Here is how I refactored the marshaling/unmarshaling methods:
```go
// MarshalJSON implements a marshaling function for time-related claims.
func (t Time) MarshalJSON() ([]byte, error) {
	if t.Before(internal.Epoch) {
		return json.Marshal(0)
	}
	return json.Marshal(t.Unix())
}

// UnmarshalJSON implements an unmarshaling function for time-related claims.
func (t *Time) UnmarshalJSON(b []byte) error {
	var unix *int64
	if err := json.Unmarshal(b, &unix); err != nil {
		return err
	}
	if unix == nil {
		return nil
	}
	tt := time.Unix(*unix, 0)
	if tt.Before(internal.Epoch) {
		tt = internal.Epoch
	}
	t.Time = tt
	return nil
}
```

**Comment by gbrlsnchs** [comment]
I need to merge this to `master` because this brings compatibility with Go 1.9.7+ and 1.10.3+ and I need to release a new `beta` version. However, feel free to give me feedback by opening issues while it's in beta/RC phase. After that, it will get harder to make changes because API cannot be changed without a major bump.

**Comment by seh** [comment]
That's fine. [Your description of your approach](https://github.com/gbrlsnchs/jwt/pull/30#issuecomment-509786101) sounds workable. I'll try porting onto the new interface in the near future, and share feedback as it occurs to me.

**Comment by gbrlsnchs** [comment]
Okay! Thanks for your help!

**Pull request closed without merging**
